travis:
  secure:
    BINSTAR_TOKEN: 2vDxJ9DXCkbRIAV4G3CEJFbJ4IvC6ev55xI9qiEiLaU1ehFeoGoksZh06V/2+QjKuxrmgAPcMcgVScHBPM3JsutyUiVCA1MDgAc1zA1wyhTQWH9UiGWMWei/O1tDk5yUBpwJwh/7cCYra5QYn8O6oRxOQpDx/zmgi/HamvjdzoOUHLCrgpWFpcFtr7nA2w7dd/ZVGTYzksqgtQuseum4ye7v4tbYidJJx1zI4NehnMbIcRHZyKGNnkQhIzibxnDwBPRYTGJQpJ3NpwhALBBTcETEp4/zLcUMqatvHViPhHqmcQM2W0zdGmCwkp7mvodRH/ra/ZXANYfilCatSXxAcOb97t3PQffNhaDM7VZw+/++czQYqlDWJZAl+SuDaaIhHqH59nOomoprOK5X72Z+CrEP/vz99Wj+fnTZfHcJAgRh3MshgaULyviHPJ8IsjPT8t10zVVz7gYIHb6HZPxAKa77qKSeaexdzW2tuL0S0jOB7xMIp/j3aOH/E4ikFv/f6cKuas/6pSDp0sPJ5kRM/TeJrdW0ZyLZ+Ngp5MFUhze/2db5xzpBHIKtrwItrS9FvmPJOtUvPYy9YVIjNuCEPVKKL8T7IEKdZiCOAMqriK6tc4csLVqZ5oAS+ZW5a2kzmgK5pg4hyfaZQ5OPMd1szk/jnrBD3P4+yjfYMIMa37o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
